### ISSUE TITLE
Could you please upload the 'creator_VGG19_model.h5' file?

### ISSUE THREAD

**Issue by Hannah-Yao** [paintception/Deep-Transfer-Learning-for-Art-Classification-Problems#4]
Hi, I am playing on your 'from_one_art_to_another' task with my dataset. But it doesn't work, since there is no RijksVGG19Net model can be loaded, just 'creator_VGG19_weights.h5' is found. Could you please also upload the 'creator_VGG19_model.h5' file?  Thank you.

**Comment by paintception** [comment]
Hi, unfortunately, the .h5 file wat too big to push it on GitHub. 

I still have the files of all the models though so I can share them with you via email or so, you can contact me at m.sabatelli@uliege.be :-)

**Comment by Hannah-Yao** [comment]
> Hi, unfortunately, the .h5 file wat too big to push it on GitHub.
> 
> I still have the files of all the models though so I can share them with you via email or so, you can contact me at [m.sabatelli@uliege.be](mailto:m.sabatelli@uliege.be) :-)

Really appreciate it! Will contact you via email soon：D

**Comment by Hannah-Yao** [comment]
> > Hi, unfortunately, the .h5 file wat too big to push it on GitHub.
> > I still have the files of all the models though so I can share them with you via email or so, you can contact me at [m.sabatelli@uliege.be](mailto:m.sabatelli@uliege.be) :-)
> 
> Really appreciate it! Will contact you via email soon：D

Hi Matthia, probably my email was sent to your junk box.   Could please have a check. Thxxx!
(ps: my email is someone.qing@gamil.com)

**Comment by wdoppenberg** [comment]
I sent you an email about this as well, I don't know if it ended up in your junk folder.
